// <auto-generated />
using GAME_MAN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAME_MAN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240910124645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GAME_MAN.Models.Score", b =>
                {
                    b.Property<int>("ID_score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_score"));

                    b.Property<int>("Score_number")
                        .HasColumnType("int");

                    b.HasKey("ID_score");

                    b.ToTable("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
